#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

# Orange Pi Zero 2W is arm64 (Allwinner H618, Cortex-A53)
BASE_ARCH="arm64"

# Image source
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}/armbian-orangepi_zero2w_bookworm.img.xz.sha256"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}/armbian-orangepi_zero2w_bookworm.img.xz"

# export Variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
